"""Quadrature shock grid — Gauss-Hermite product nodes + disaster/no-shock nodes.

Faithful port of the shock-grid block of `mod_param.f90 :: init_setup`
(lines ~263-430). Four normal shocks in order [z, zf, p(=disaster prob), omg],
each discretized by Gauss-Hermite; the product grid has n_GH = prod(n_quad_*)
nodes, plus a no-shock node and a disaster node (n_quad = n_GH + 2).

Correlated shocks are generated by mapping the standardized product nodes through
the Cholesky factor of the shock covariance. NOTE — replicating the Fortran
EXACTLY: it factors the covariance with LAPACK dpotrf('U') (A = Uᵀ U, U upper) and
forms shock_i = sum_j U(i,j) z_j, i.e. shock = U z (so the node second-moment
matrix is U Uᵀ). Only the disaster(3)–omg(4) block is correlated. This U-vs-Uᵀ
convention is KL's; we match it rather than "fix" it (faithful refactor).

Setup-time host computation; returns float64 device tensors used in the solver.
"""
from dataclasses import dataclass

import numpy as np
import torch

from ..config import DTYPE
from ..params import Params, SQRT_EPS
from ..quad.gauss_hermite import gauss_hermite_nb


@dataclass
class ShockGrid:
    shock_grid: torch.Tensor      # (n_quad, 4) shock realizations per node
    quad_weight_vec: torch.Tensor  # (n_GH + 1,) product-node weights (+0 no-shock)
    dz_vec: torch.Tensor           # (n_quad,) the z-shock column
    dz_vec_adj: torch.Tensor       # (n_quad,) dz_vec with disaster node zeroed
    chol_upper: torch.Tensor       # (4, 4) the U factor actually used
    n_quad: int
    n_gh: int
    no_shock_idx: int              # 0-based index of the no-shock node


def build_shock_grid(p: Params, *, dtype=DTYPE, device=None) -> ShockGrid:
    nq = p.n_quad_shocks  # [z, zf, p, omg]
    n_gh = nq[0] * nq[1] * nq[2] * nq[3]
    n_quad = n_gh + 2

    # Per-shock GH nodes/weights (n==1 -> node 0, weight 1, matching the Fortran).
    nodes, weights = [], []
    for n in nq:
        x, w = gauss_hermite_nb(n)
        nodes.append(x.numpy())
        weights.append(w.numpy())

    # Shock covariance (upper triangle populated as in the Fortran), then made
    # symmetric for the factorization.
    cov = np.zeros((4, 4), dtype=np.float64)
    cov[0, 0] = p.sig_z ** 2
    cov[1, 1] = p.sig_zf ** 2
    cov[2, 2] = p.sig_dis ** 2
    cov[3, 3] = p.sig_omg ** 2
    if p.corr_omg_dis < 1.0 - SQRT_EPS and p.omg_std > SQRT_EPS:
        cov[2, 3] = p.sig_omg * p.sig_dis * p.corr_omg_dis
    # Zero-vol guards so the factorization is PD (mod_param.f90:298-306).
    if p.sig_z == 0.0:
        cov[0, 0] = 1.0
    if p.sig_zf == 0.0:
        cov[1, 1] = 1.0
    if p.sig_dis == 0.0:
        cov[2, 2] = 1.0

    cov_sym = cov + cov.T - np.diag(np.diag(cov))
    # numpy gives lower L with cov = L Lᵀ; U = Lᵀ is the dpotrf('U') factor (cov = Uᵀ U).
    U = np.linalg.cholesky(cov_sym).T

    # omg perfectly correlated with disaster and zero-vol: zero out omg post-factor
    # (mod_param.f90:313-316). Edge case; benchmark uses corr=0.5 so this is inert.
    if p.omg_std == 0.0 and p.corr_omg_dis == 1.0:
        U[3, :] = 0.0
        U[:, 3] = 0.0

    corr_collapse = p.corr_omg_dis > 1.0 - SQRT_EPS

    shock_grid = np.zeros((n_quad, 4), dtype=np.float64)
    quad_weight = np.zeros(n_gh + 1, dtype=np.float64)
    counter = 0
    for ggg in range(nq[0]):
        for zzz in range(nq[1]):
            for ddd in range(nq[2]):
                for www in range(nq[3]):
                    if corr_collapse:
                        z = np.array([nodes[0][ggg], nodes[1][zzz],
                                      nodes[2][ddd], nodes[2][ddd]])
                    else:
                        z = np.array([nodes[0][ggg], nodes[1][zzz],
                                      nodes[2][ddd], nodes[3][www]])
                    shock_grid[counter, :] = U @ z  # shock = U z (Fortran convention)
                    quad_weight[counter] = (weights[0][ggg] * weights[1][zzz]
                                            * weights[2][ddd] * weights[3][www])
                    counter += 1

    # No-shock node (0-based index n_gh): zeros, weight 0.
    quad_weight[n_gh] = 0.0
    # Disaster node (0-based index n_gh+1 = n_quad-1): only a z drop.
    shock_grid[n_quad - 1, 0] = -p.disast_shock

    dz_vec = shock_grid[:, 0].copy()
    dz_vec_adj = dz_vec.copy()
    dz_vec_adj[n_quad - 1] = 0.0

    t = lambda a: torch.tensor(a, dtype=dtype, device=device)
    return ShockGrid(
        shock_grid=t(shock_grid),
        quad_weight_vec=t(quad_weight),
        dz_vec=t(dz_vec),
        dz_vec_adj=t(dz_vec_adj),
        chol_upper=t(U),
        n_quad=n_quad,
        n_gh=n_gh,
        no_shock_idx=n_gh,
    )
